# Generated by Django 5.1.7 on 2025-03-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                ("account_id", models.UUIDField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "bank_account_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "currency_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("tax_type", models.CharField(blank=True, max_length=50, null=True)),
                ("enable_payments_to_account", models.BooleanField(default=False)),
                ("show_in_expense_claims", models.BooleanField(default=False)),
                ("class_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "system_account",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reporting_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reporting_code_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("has_attachments", models.BooleanField(default=False)),
                ("updated_date_utc", models.DateTimeField(blank=True, null=True)),
                ("add_to_watchlist", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Chart of Account",
                "verbose_name_plural": "Chart of Accounts",
                "ordering": ["account_id"],
            },
        ),
        migrations.CreateModel(
            name="XeroToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("expires_in", models.IntegerField()),
            ],
            options={
                "verbose_name": "Xero Token",
                "verbose_name_plural": "Xero Tokens",
            },
        ),
    ]
