# Generated by Django 5.1.7 on 2025-03-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("xero", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chartofaccount",
            options={
                "ordering": ["name"],
                "verbose_name": "Chart of Account",
                "verbose_name_plural": "Chart of Accounts",
            },
        ),
    ]
